sudo: false
language: python
python: '3.5'
env:
  global:
    - GITHUB_REPO: "pstauffer/Microservices_with_Kubernetes"
    - secure: ri9A8kVL7HPwcruzrwcN/PGsKw0M8S2SbZMt6Q098q7xWwGeVLUqkxvI41uFYIdSmAYlqDxS/SGNuEVTBwrU35SNuWwvTcPShofNQenk6jO7R/QGzDn+hvkTLyqG5zwvewL+P+KDQpyy2sm6brrN5dmezZYdvq2T8TI9tawHxQNQPSP78R3HRh/p9JsvmmDCWq9L8lOIaKW+j6UkEqZMKqxPyPA9KNZ0Nb35ARQ4kfhbmjCrzxwmKZ3ZNeDWNml2amxAUVeJ1Siwv/pvD8q778jOGIrpMRQZ6gF9jCcxnz2jHlzPB4kJq9H8YmFctttfxauvUEhVNVXixdeOIoo7ZoGgLlMdnJk6+CAIItIo696abTTDd8l4cwJJB4KFd5jmH+D39Pe6pe5hQBUrKTHm6VKFOfgHKgBHXvBR2IaRnTbN3RyZ1yiTbOqbTERf2f6jACgVIFHWdSy1S9g2fvPbYI1ftcy8xWVtW3VPOZnge7gcpoJQaXwPa8ptSKKwsvLKZTyYvdYKKOMUt7aMdJdPvebQlkpHnGlq7n4+kAYxp3B38QdGPuNfJYn6UU9t3V0dbsa45HhXchIa4vRZFcY0Pl2nGPNUGfe7uBQTaSe8/2gKrFJqfVpepdKpmuUKJsZ1IXnaruDBkd7xVfpIk5qSfBV2Outz2Pj+jOgEN+YOgds=

install:
- pip install mkdocs
script:
- ls -l
- git config --global user.email "pascal@github.com"
- git config --global user.name "Travis CI"
- cd mkdocs && mkdocs build
- cd ../../site && ls -l
- git init
- git add .
- git commit -m "Deploy to Github Pages"
- git push --force --quiet https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git master:gh-pages
